- name: Log in to Docker registry
  docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ docker_user }}"
    password: "{{ docker_pass }}"

- name: Run containers
  docker_container:
    name: "echo-server-{{ item }}"
    image: tyumin000/devopscloudrucamp:echo-server-latest
    restart_policy: unless-stopped
    env:
      AUTHOR: "Nikita"
    networks:
      - name: echo-server-network
  loop: [1, 2, 3]
