apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-credentials
  namespace: echo-server
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\"}}}" .Values.dockerRegistry.server .Values.dockerRegistry.username .Values.dockerRegistry.password .Values.dockerRegistry.email | b64enc }}
